name: 'Setup Environment'
description: 'Setup Environment'

inputs:
  script-path:
    description: 'Script Path'
    required: true
    default: ''
  script-arguments:
    description: 'Script Arguments'
    required: false
    default: ''
  use-jurpel-qt-action:
    description: 'Use jurpel/qt-action'
    required: false
    type: boolean
    default: true
  qt-version:
    description: 'Qt Version - used with jurpel/qt-action'
    required: false
    default: '5.15.2'
  

runs:
  using: "composite"
  steps:
    - name: Setup MSVC
      uses: ilammy/msvc-dev-cmd@v1
    - name: Check
      shell: bash
      run: |
        echo "Install Qt Action: ${{ inputs.use-jurpel-qt-action }}"
    - name: Install Qt
      if: inputs.use-jurpel-qt-action == 'true'
      uses: jurplel/install-qt-action@v3
      with:
        cache: true
        version: ${{ inputs.qt-version }}
    - name: Install dependencies
      if: inputs.use-jurpel-qt-action == 'true'
      shell: bash
      run: |
        bash ${{ inputs.script-path }} ${{ inputs.script-arguments }}