name: 'Build'
description: 'Build'

inputs:
  script-path:
    description: 'Script Path'
    required: true
    default: ''
  script-arguments:
    description: 'Script Arguments'
    required: false
    default: ''
  ccache-key:
    description: 'Ccache Key'
    required: false
    default: ''
  cache-path:
    description: 'Directory to cache after build'
    required: false
    default: ''
  cache-key:
    description: 'Cache key'
    required: false
    default: ''

runs:
  using: "composite"
  steps:
    - name: Cache external libraries sources
      id: cache-ext-libs
      if: ${{ inputs.cache-path != '' }}
      uses: actions/cache@v4
      with:
        path: ${{ inputs.cache-path }}
        key: ${{ runner.os }}-${{ inputs.cache-key }}
    - name: Ccache
      uses: hendrikmuhs/ccache-action@v1.2
      with:
        key: ${{ matrix.os }}-${{ github.ref }}-${{ inputs.ccache-key }}
    - name: Configure and Build
      shell: bash
      run: |
        bash ${{ inputs.script-path }} ${{ inputs.script-arguments }}